[project]
name = "clash-royale-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.6.0",
    "pytest>=8.3.5",
    "requests>=2.32.3",
    "python-dotenv>=1.0.0",
]
