services:
  chat-royale-backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
      target: development
    container_name: chat-royale-backend-dev
    ports:
      - "3001:3001"
    env_file:
      - src/backend/.env
    environment:
      - PORT=3001
      - NODE_ENV=development
    volumes:
      - ./src/backend/src:/app/src
      - ./src/backend/package.json:/app/package.json
      - ./src/backend/tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      clash-royale-mcp-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - chatroyale-network

  clash-royale-mcp-server:
    build:
      context: ./src/mcp
      dockerfile: Dockerfile
    container_name: clash-royale-mcp-server-dev
    ports:
      - "8000:8000"
    env_file:
      - src/mcp/.env
    volumes:
      - ./src/mcp/src:/app/src
      - ./src/mcp/pyproject.toml:/app/pyproject.toml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/mcp"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - chatroyale-network

  chat-royale-frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      target: development
      args:
        VITE_API_BASE_URL: http://localhost:3001
    container_name: chat-royale-frontend-dev
    ports:
      - "8080:5173"
    volumes:
      - ./src/frontend/src:/app/src
      - ./src/frontend/public:/app/public
      - ./src/frontend/package.json:/app/package.json
      - ./src/frontend/vite.config.ts:/app/vite.config.ts
      - ./src/frontend/tailwind.config.js:/app/tailwind.config.js
      - ./src/frontend/index.html:/app/index.html
      - /app/node_modules
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - chatroyale-network

networks:
  chatroyale-network:
    driver: bridge 