version: '3.8'

services:
  claude-chat-backend:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - src/backend/.env
    environment:
      - PORT=3001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 